// object update actioons
export const UPDATE_TOTAL = 'UPDATE_OBJECT_COUNT_TOTAL';
export const UPDATE_COUNT = 'UPDATE_OBJECT_COUNT_SCANNED';

// error actions
export const ADD_ERROR = 'ADD_ERROR';
export const FIX_ERROR = 'FIX_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

// warning actions
export const ADD_WARNING = 'ADD_WARNING';
export const FIX_WARNING = 'FIX_WARNING';
export const REMOVE_WARNING = 'REMOVE_WARNING';

// info actions
export const ADD_INFO = 'ADD_INFO';
export const FIX_INFO = 'FIX_INFO';
export const REMOVE_INFO = 'REMOVE_INFO';

// api actions
export const API = 'API';

// settings actions
export const TOGGLE_APP_THEME = 'TOGGLE_APP_THEME';

// session actions
export const CONNECT_FROM_UI_TO_REVIT = 'CONNECT_FROM_UI_TO_REVIT';
export const CONNECT_FROM_REVIT_TO_UI = 'CONNECT_FROM_REVIT_TO_UI';
export const INITIAL_UI_CONNECTION = 'INITIAL_UI_CONNECTION';
export const INITIAL_UI_CONNECTION_SUCCESS = 'INITIAL_UI_CONNECTION_SUCCESS';
export const INITIAL_UI_CONNECTION_FAILED = 'INITIAL_UI_CONNECTION_FAILED';
export const PROCESS_CONNECTION_PARAMETERS = 'PROCESS_CONNECTION_PARAMETERS';
export const STORE_CONNECTION_PARAMETERS = 'STORE_CONNECTION_PARAMETERS';
export const STORE_SOCKET_ID = 'STORE_SOCKET_ID';
export const STORE_COMPLETE_ID = 'STORE_COMPLETE_ID';
export const SET_SESSION_STATE = 'SET_SESSION_STATE';
export const SET_UI_SOCKET_ID = 'SET_UI_SOCKET_ID';
export const SOCKET_LINK_SUCCESS = 'SOCKET_LINK_SUCCESS'
export const SOCKET_LINK_FAILED = 'SOCKET_LINK_FAILED'

// socket actions
export const WS_CONNECT = 'WS_CONNECT';
export const WS_CONNECTED = 'WS_CONNECTED';
export const WS_DISCONNECT = 'WS_DISCONNECT';
export const WS_DISCONNECTED = 'WS_DISCONNECTED';
export const WS_INITIALIZE_BEGIN = 'WS_INITIALIZE_BEGIN';
export const WS_INITIALIZE_SUCCESS = 'WS_INITIALIZE_SUCCESS';
export const WS_INITIALIZE_FAILURE = 'WS_INITIALIZE_FAILURE';
export const WS_REGISTER_EVENT = 'WS_REGISTER_EVENT';

// commands
export const COMMAND_BACKUP = 'COMMAND_BACKUP';
export const FAKE_UPDATE = 'FAKE_UPDATE';
export const SCAN_COUNT_CHANGED = 'SCAN_COUNT_CHANGED';
export const SCAN_TOTAL_CHANGED = 'SCAN_TOTAL_CHANGED';
